### ISSUE TITLE
How ready is this project for production?

### ISSUE THREAD

**Issue by xwartz** [hieuvp/react-native-fingerprint-scanner#1]
I've been very interested in this project. I'm actually shocked to find this. I had searched a bunch projects. It's the only one which is compatible with iOS and Android.  How ready is this to be used in production?

**Comment by hieuvp** [comment]
Hi @xwartz,

I'm glad that you are going to use this library for your project!
My team had faced exactly same situation as you did. After a few days for investigating into React Native open source community, we ended up by a cool decision, pick some of selective mature libraries in Native mobile world and to port them to React Native.

I can answer you that, we're using this 'react-native-fingerprint-scanner' module for a quite big Bank in Indonesia. We're constantly improving quality as well as resolving issues while integrating to our main project.
For now, this library is 95% stable, the API is not likely to change much.

Thank you!

**Comment by xwartz** [comment]
Hi, @hieuvp  
Thank you for the quick reply! 
But it is not worked for me in react-native v0.37.

**Comment by hieuvp** [comment]
Sorry mate! this library only supports react native version >= v0.40

**Comment by hieuvp** [comment]
Hi,

React Native significantly changes much while they're still in 0.x.x,
Better not to support version below 0.40!
Anyways, you can refer to this link to upgrade your current project:
https://facebook.github.io/react-native/docs/upgrading.html

You'll gain lot of benefits from it.

**Comment by xwartz** [comment]
@hieuvp I have created a [PR](https://github.com/hieuvp/react-native-fingerprint-scanner/pull/2) to back compatibility for RN version < 0.40. And it is worked for me.

**Comment by hieuvp** [comment]
Thanks @xwartz, I will review it again and consider to have support for RN < 0.40.0

**Comment by xwartz** [comment]
Thanks. @hieuvp
