### ISSUE TITLE
ios 13.3 , faceID try again not working

### ISSUE THREAD

**Issue by razzbee** [hieuvp/react-native-fingerprint-scanner#111]
On iPhone 11 (iOS 13.3) stimulator, the try again on the faceID prompt doesn't work after fail, any solution??

**Comment by phillbaker** [comment]
Hi @razzbee, can you include the output of `react-native info`? And what version of this library are you using?

**Comment by phillbaker** [comment]
Hi @razzbee, since I haven't heard back with any further details and there is no reproducible example attached to this issue, I'm going to close this issue for now. Please re-open if if you can provide more information.
