### ISSUE TITLE
Language Translation for Cancel Text and Bio metric type text

### ISSUE THREAD

**Issue by Ramaraju1992** [hieuvp/react-native-fingerprint-scanner#114]
Hi,
We are trying to change language translations for **description** in confirm bio metric  popup using 
```
const authOptions = {
            description: translate('confirmYourFingerprint'),,
            onAttempt: this.handleAuthenticationAttempted,
        };
```
it is working as expected.
And when we try to change the language for _cancel_ button text, we are unable to find where we can change.
please help us to change language translations for  **cancel** button text and **Bio Metric** type text

**Comment by phillbaker** [comment]
To confirm @Ramaraju1992, you're using an iOS device? If so, the prompt is system generated and only accepts a description, not text for the action buttons. Those buttons should be translated as per the system language, so whatever language the user has set on their phone will be used.

**Comment by Ramaraju1992** [comment]
Hai @phillbaker ,
Yes i am facing issue in iOS device only.
in android i was able change texts as expected.
thanks for update.
