### ISSUE TITLE
[v4.0.0] reject is not defined

### ISSUE THREAD

**Issue by rajaishwary** [hieuvp/react-native-fingerprint-scanner#116]
"react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-fingerprint-scanner": "4.0.0" [downloaded zip]

@fkotsian tried lib new version with build tools 29. face unlock didn't come up and got below issue after successful fingerprint scan.
![image](https://user-images.githubusercontent.com/7762321/73137768-e549cf80-4081-11ea-8dee-f298f81b2f90.png)

**Comment by fkotsian** [comment]
@rajaishwary Ty I will take a look

**Comment by rajaishwary** [comment]
@fkotsian I have checked the code, I think while refactoring the code. it was missed. I will create a PR for this small fix, so new release will be at working state.

**Comment by fkotsian** [comment]
@rajaishwary Thanks for your help, 4.0.0 includes your PR and is available on NPM: https://www.npmjs.com/package/react-native-fingerprint-scanner/v/4.0.0

**Comment by rajaishwary** [comment]
Great, thanks for the update @fkotsian :)
