### ISSUE TITLE
The implementation android example is wrong

### ISSUE THREAD

**Issue by maoapp** [hieuvp/react-native-fingerprint-scanner#118]
The android example  has three errors  in the componentDidmount
the functions are being called in this way: 
`  componentDidMount() {
    if (requiresLegacyAuthentication()) {
      authLegacy();
    } else {
      authCurrent();
    }
  }`

instead of use the context (this)

`  componentDidMount() {
    if (this.requiresLegacyAuthentication()) {
      this.authLegacy();
    } else {
      this.authCurrent();
    }
  }`

**Comment by phillbaker** [comment]
Hello, thanks for opening an issue. Are you referring to the example in the
README? Would you like to submit a PR with the corrections?

**Comment by maoapp** [comment]
@phillbaker yes , I refer to the example and of course I will create the PR in order to fix this, thanks.

**Comment by maoapp** [comment]
https://github.com/hieuvp/react-native-fingerprint-scanner/pull/122

**Comment by phillbaker** [comment]
fixed in https://github.com/hieuvp/react-native-fingerprint-scanner/pull/122
