### ISSUE TITLE
pod can`t install

### ISSUE THREAD

**Issue by xclidongbo** [hieuvp/react-native-fingerprint-scanner#127]
RN0.59.10
react-native-fingerprint-scanner@2.6.2
pod install
```
$ pod install
Analyzing dependencies
[!] No podspec found for `ReactNativeFingerprintScanner` in `../node_modules/react-native-fingerprint-scanner`
```

**Comment by phillbaker** [comment]
> react-native-fingerprint-scanner@2.6.2

The podspec was only added in v3 (https://github.com/hieuvp/react-native-fingerprint-scanner/commit/7e828060e30274c6def68bf5b01dd8af28954586). You'll need to upgrade react-native and update to a more recent version of the library.

Closing for now, please re-open if there are other issues.
