### ISSUE TITLE
make setNegativeButtonText configurable

### ISSUE THREAD

**Issue by soumyamishra89** [hieuvp/react-native-fingerprint-scanner#128]
setNegativeButtonText is set to "Cancel" and is not configurable on Android biometrics prompt.
I can make a PR for this, if anyone else do not have the time for it.

**Comment by mikehardy** [comment]
".. should be ..." in open source usually should be re-phrased to "would you mind if I made a PR for .. so it ...", usually about as fast as logging an issue, and with https://github.com/ds300/patch-package you can adopt your change in a safe way immediately while the PR works its way through approval

**Comment by soumyamishra89** [comment]
That makes lot of sense. Thank you for the info. I will update accordingly.

**Comment by phillbaker** [comment]
Fixed in  #120
