### ISSUE TITLE
Support RN > 0.47

### ISSUE THREAD

**Issue by harishsn** [hieuvp/react-native-fingerprint-scanner#13]
/node_modules/react-native-fingerprint-scanner/android/src/main/java/com/hieuvp/fingerprint/ReactNativeFingerprintScannerPackage.java:20: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-fingerprint-scanner:compileReleaseJavaWithJavac FAILED

**Comment by amitpadmani** [comment]
getting same issue.. #harishsn you find any solution ?

**Comment by harishsn** [comment]
remove @override inside FingerprintPackage.java for createJSModules method.. That should work as a temp fix.

**Comment by hoangnm** [comment]
It's been fixed, https://github.com/hieuvp/react-native-fingerprint-scanner/pull/15. Closing.
