### ISSUE TITLE
Android app getting crashed after updating package to 4.0.0

### ISSUE THREAD

**Issue by sumerpatel** [hieuvp/react-native-fingerprint-scanner#132]
After updating react-native-fingerprint-scanner package to latest version android app started getting crashed. Attached a screenshot of the error.

Here is my code : -

error: ReactNativeFingerprintScanner.authenticate got 2 arguments, expected 3

> FingerprintScanner.authenticate({
        onAttempt: this.handleAuthenticationAttempted,
      })
        .then(() => {
          this.handleSuccess(labels);
        })
        .catch((error: { message: any }) => {
          this.setState({ errorMessage: error.message });
        });

<img width="407" alt="Screenshot 2020-04-24 at 7 53 03 AM" src="https://user-images.githubusercontent.com/22316368/80168698-2b6eea80-8601-11ea-8aec-5b7799d1afae.png">

**Comment by mikehardy** [comment]
if you update and start having problems, always try `npx react-native-clean-project` first to blow out any of the caches that might have stale version code in them

**Comment by sumerpatel** [comment]
this didn't work

**Comment by mikehardy** [comment]
How did it work when you cloned this repo and used the example? If it works, your local project has a problem, but the module is fine, and it's not a bug, it's a project problem you'll have to figure out

**Comment by sahil290791** [comment]
@sumerpatel what is RN version, Platform ios? android? and OS version?

**Comment by sumerpatel** [comment]
@sahil290791  RN : 0.62.2, Platform - Android, OS version - 10

**Comment by NaNtrack** [comment]
The same error with:
Android 28, 29, R
react-native: 0.59.10

**Comment by mikehardy** [comment]
> How did it work when you cloned this repo and used the example?

**Comment by NaNtrack** [comment]
i had the old bundle and map files in:

```
android/app/src/main/assets/index.android.bundle
android/app/src/main/assets/index.android.map
```

after recreating those files start working again

`react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --sourcemap-output android/app/src/main/assets/index.android.map --assets-dest android/app/src/main/res/`

**Comment by mikehardy** [comment]
@NaNtrack do not do that! Never copy built assets into the src tree.

This was the source of many problems, a PR directly into react-native, and then a revert of that PR. There is a correct way to do the bundle, and this is it: https://github.com/facebook/react-native/issues/22234#issuecomment-504721069

**Comment by NaNtrack** [comment]
we dont have those files versioned on git, so no worries...

**Comment by mikehardy** [comment]
> we dont have those files versioned on git, so no worries...

If you read that thread you'll realize it causes problems in local builds frequently, like you experienced. I also had those files .gitignore'd but it still blows up your local environment and/or masks changes you make (like software version upgrades).

If that's how you want to develop, okay, but given there's a posted solution that works and the way you're doing it (and the way I was doing it) was conclusively shown to be wrong, seems odd to want to keep doing it.

**Comment by NaNtrack** [comment]
> > we dont have those files versioned on git, so no worries...
> 
> If you read that thread you'll realize it causes problems in local builds frequently, like you experienced. I also had those files .gitignore'd but it still blows up your local environment and/or masks changes you make (like software version upgrades).
> 
> If that's how you want to develop, okay, but given there's a posted solution that works and the way you're doing it (and the way I was doing it) was conclusively shown to be wrong, seems odd to want to keep doing it.

thanks for the advice, we will find a better solution to avoid this problems in the future

**Comment by sumerpatel** [comment]
> > How did it work when you cloned this repo and used the example?

Created a new RN project with version 0.61.5 and it still didn't work.

**Comment by mikehardy** [comment]
new project != clone repo + use example, I'm very curious if the example in this repo works
if it does, then what is the difference between the example and a fresh project?
