### ISSUE TITLE
Sometimes the modal doesn't show on iOS and Android

### ISSUE THREAD

**Issue by SMJ93** [hieuvp/react-native-fingerprint-scanner#139]
Hi, first of all great library. Managed to get it working in no time!

Is there a reason the modal doesn't always show? It triggers the onSuccess callback but I never see the modal. This happens on both iOS and Android.

I am using:  version `5.0.0` with react-native `0.62.2`

I am using functional components:

```
useEffect(() => {
if (isIOS) {
    FingerprintScanner.authenticate({
      description: 'Scan your fingerprint on the device scanner to continue',
    })
      .then(() => onSuccess())
      .catch((error) => {
        biometricsErrorHandler(error);
        onError();
      });
  } else {
    FingerprintScanner.authenticate({title: 'Log in with Biometrics'})
      .then(() => onSuccess())
      .catch((error) => {
        biometricsErrorHandler(error);
        onError();
      });
  }
}, [],
```

**Comment by Dwayne01** [comment]
what was the solution to this issue

**Comment by SMJ93** [comment]
Hi @Dwayne01, 

I think it was conflicting with another library if I remember correctly.
