### ISSUE TITLE
Activate a second time FingerprintScanner.authenticate

### ISSUE THREAD

**Issue by EmilMakaev** [hieuvp/react-native-fingerprint-scanner#157]
Android. When I activate biometrics for the first time and click (cancel), I get an errors (UserCancel or UserFallback) That's okay, but when I activate (FingerprintScanner.authenticate) a second time it doesn't return Promise, I don't get into (then, catch) block. Biometrics works, but the result is not resolved. Please tell me why this is happening?

If I restart the applications, then everything works, but also only with the first activation of biometrics, with the second activation, nothing works.

**Comment by stephichau** [comment]
@EmilMakaev this might help https://github.com/hieuvp/react-native-fingerprint-scanner/issues/155

**Comment by EmilMakaev** [comment]
> @EmilMakaev this might help #155

Thank you very much!
