### ISSUE TITLE
When isSensorAvaiable catched error will run into forever loop

### ISSUE THREAD

**Issue by jamesduan** [hieuvp/react-native-fingerprint-scanner#17]

**Comment by dinhtu0802** [comment]
+1

**Comment by phillbaker** [comment]
Hi all, I've recently been added to this repo as a collaborator and am getting up to speed on the different issues. I don't quite follow this bug report - is there a simple code snippet that can help reproduce this?

**Comment by phillbaker** [comment]
Going to close as there's been to no follow up. Please re-open if there's a reliable reproduction of this bug.
