### ISSUE TITLE
FingerprintScanner  authenticate promise result always return true

### ISSUE THREAD

**Issue by eashevchenko** [hieuvp/react-native-fingerprint-scanner#18]
When I have used FingerprintScanner authenticate method and check it on xCode emulator - Touch ID Matching touch - promise return true and Non-matching touch - also return true. How I can fix this ?

**Comment by atom-r** [comment]
I'm also seeing this.

**Comment by sahil290791** [comment]
I am also facing this same issue. When will the [fix](https://github.com/hieuvp/react-native-fingerprint-scanner/pull/19) be merged?

**Comment by hieuvan-pycogroup** [comment]
Hi @sahil290791,

I am checking it now, you will have an updated version after an hour.

Thank you!
