### ISSUE TITLE
null is not an object (evaluating o.isSensorAvailable)

### ISSUE THREAD

**Issue by ahsanparacha02** [hieuvp/react-native-fingerprint-scanner#186]
When i run in debug mode everything is working fine, but when i test in release apk then i can get this error.

Please help me to fixed this issue

Thanks

**Comment by mikehardy** [comment]
Hi there, if it works in debug, it should work in release, or there is something wrong with your project and something different in the settings used between debug and release mode 

This issue does not contain sufficient information to troubleshoot, either way https://stackoverflow.com/help/minimal-reproducible-example
