### ISSUE TITLE
JCenter will not be maintained anymore

### ISSUE THREAD

**Issue by keremoge** [hieuvp/react-native-fingerprint-scanner#188]
On February 3 2021, JFrog [announced that they will be shutting down JCenter.](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

Instead we should use **mavenCentral()**

Any plan on replacing jCenter() in [build.gradle](https://github.com/hieuvp/react-native-fingerprint-scanner/blob/master/android/build.gradle) ?

Current error if we replace **jCenter()** with **mavenCentral()** :

> `Could not resolve com.wei.android.lib:fingerprintidentify:1.2.6`

**Comment by mikehardy** [comment]
Hi there! I believe you're in the wrong spot - that's a *transitive* dependency in your project, via this project, but the real dependency is elsewhere.

You might like: https://github.com/uccmawei/FingerprintIdentify/commit/5a344dcbbfbdf4d70299d1cabaa8d47e57600e19

**Comment by keremoge** [comment]
Yes you are are right the root problem is about [FingerprintIdentify](https://github.com/uccmawei/FingerprintIdentify), but since this repository is using it the problem is also affecting [react-native-fingerprint-scanner](https://github.com/hieuvp/react-native-fingerprint-scanner) itself indirectly.

in [build.gradle](https://github.com/hieuvp/react-native-fingerprint-scanner/blob/master/android/build.gradle): 
`implementation "com.wei.android.lib:fingerprintidentify:${safeExtGet("fingerprintidentify", "1.2.6")}"`

**Comment by mikehardy** [comment]
Yes, and if you add jitpack as in the issue I reference, you're all set

**Comment by mikehardy** [comment]
Fixed by #189
