### ISSUE TITLE
Grammar issue in README.

### ISSUE THREAD

**Issue by CryceTruly** [hieuvp/react-native-fingerprint-scanner#190]
Thanks, everyone for the great work on this project.

There is a slight issue with the `NSFaceIDUsageDescription` in `info.plist`
I think the string can be ```$(PRODUCT_NAME) requires FaceID access to allow you quick and secure access.```

**Comment by mikehardy** [comment]
Hi there @CryceTruly ! Please open a PR if you want to make this change, I can merge it
