### ISSUE TITLE
Could not find com.wei.android.lib:fingerprintidentify:1.2.6

### ISSUE THREAD

**Issue by msvargas** [hieuvp/react-native-fingerprint-scanner#194]
Hello, 

I try to install react-native-fingerprint-scanner 6.0 in my project with React Native 0.65.1, I have the following error with Android, in iOS works fine.

![image](https://user-images.githubusercontent.com/8255332/132948385-21087f70-3a01-4aea-bbec-8aae9a9ea945.png)

Thanks

UPDATE:

I replace the gradle implementation and it works

`    implementation 'com.github.uccmawei:FingerprintIdentify:1.2.6'
`

```

System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 232.93 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /var/folders/kb/wxgzqly9771_vpjwhm96vhh00000gn/T/yarn--1631364518743-0.934589919579671/node
    Yarn: 1.22.10 - /var/folders/kb/wxgzqly9771_vpjwhm96vhh00000gn/T/yarn--1631364518743-0.934589919579671/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /Users/michaelvargas/.rvm/gems/ruby-2.7.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2, 31.0.0
      System Images: android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-S | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_262 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by mikehardy** [comment]
Duplicate #192

**Comment by msvargas** [comment]
@mikehardy  Why don't you use this, it should be working fine with any version of RN

`implementation 'com.github.uccmawei:FingerprintIdentify:1.2.6'
`

**Comment by mikehardy** [comment]
@msvargas I hadn't checked jitpack yet, so that's great if the bits are available up there. If you updated any Readme installation instructions in a PR I could merge it immediately, but I'm traveling and just haven't a phone so can't do it myself for quite a while

**Comment by mikehardy** [comment]
@msvargas I'm still traveling but then see that we actually already merged a jitpack PR 🤦 but I haven't had time for a release yet. My schedule should settle down and I can hopefully kick one out in a week or so

**Comment by msvargas** [comment]
@mikehardy That's sounds great hahaha, thanks for your package, if I can help with anything please let me know
