### ISSUE TITLE
Face Id not working in Iphone 11

### ISSUE THREAD

**Issue by RonaldThayil** [hieuvp/react-native-fingerprint-scanner#199]
I tried in iPhone 10 and it is working fine but when I use iPhone 11 the app closes automatically.

**Comment by mikehardy** [comment]
Hi there!
Any time the phrase "app crashes" is used in an issue report, it should be followed by the stack trace from native logs

**Comment by RonaldThayil** [comment]
I added this line 
"<key>NSFaceIDUsageDescription</key>
<string>$(PRODUCT_NAME) requires FaceID access to allows you quick and secure access.</string>"  in  info.plist.

After that, it works fine for me.

**Comment by RonaldThayil** [comment]
Solved the issue by changing in info.plist file

**Comment by mikehardy** [comment]
@RonaldThayil if there is something missing in the documentation (seems like there is? for install instructions on iOS?) you could hit the edit button on the README and quickly (using the github web UI, just takes a moment) propose a PR to improve it for everyone in the future
