### ISSUE TITLE
Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.    > Could not resolve com.facebook.react:react-native:+

### ISSUE THREAD

**Issue by zahoormohammed** [hieuvp/react-native-fingerprint-scanner#220]
hi, i just updated my android studio to Android Studio Dolphin | 2021.3.1 Patch , when i did run-android the build got failed, i am getting the following error.  
Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
       Required by:
         project :app
         project :app > project :react-native-async-storage_async-storage
         project :app > project :react-native-community_art
         project :app > project :react-native-community_datetimepicker
         project :app > project :react-native-masked-view_masked-view
         project :app > project :react-native-picker_picker
         project :app > project :react-native-android-location-enabler
         project :app > project :react-native-camera
         project :app > project :react-native-camera-kit
         project :app > project :react-native-device-info
         project :app > project :react-native-document-picker
         project :app > project :react-native-encrypted-storage
         project :app > project :react-native-fast-image
         project :app > project :react-native-fingerprint-scanner
         project :app > project :react-native-geolocation-service
         project :app > project :react-native-gesture-handler
         project :app > project :react-native-image-picker
         project :app > project :react-native-maps
         project :app > project :react-native-reanimated
    After lot of debugging i have found that it is because of react-native finger-scanner , I uninstalled the finger-scanner library and i removed the jcenter() from android/build.gradle, now the project is completely running fine, It seems like react-native fingerprint-scanner is not supporting new android studio update and new react native version. Please fix react-native fingerprint scanner library ,  This is a serious and needed to fixed , any help is appreciated.

**Comment by mikehardy** [comment]
Pinned issue #192, duplicate
