### ISSUE TITLE
com.wei.android.lib:fingerprintidentify not found

### ISSUE THREAD

**Issue by fcaldarelli** [hieuvp/react-native-fingerprint-scanner#237]
The library com.wei.android.lib:fingerprintidentify does not exist, because jcenter is dead.

@hieuvp Can you release a new version that points to last master commit that contains the fix?

**Comment by chamavv** [comment]
mismo problema

**Comment by mikehardy** [comment]
Duplicate, see https://github.com/hieuvp/react-native-fingerprint-scanner/issues/192

(basically, use the unreleased git version, and it should work)

**Comment by fcaldarelli** [comment]
@mikehardy why don't release a new version?

**Comment by mikehardy** [comment]
No time. How's your open source time availability + contributions? Is there ever enough time?

**Comment by fcaldarelli** [comment]
I perfectly understand. In this case the only action required should be release a new version, that point at commit you suggested in #192.

Thank you very much for your work.
