### ISSUE TITLE
issue on install package

### ISSUE THREAD

**Issue by Mdhun-kakkery** [hieuvp/react-native-fingerprint-scanner#242]
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.wei.android.lib:fingerprintidentify:1.2.6.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/wei/android/lib/fingerprintidentify/1.2.6/fingerprintidentify-1.2.6.pom
       - https://repo.maven.apache.org/maven2/com/wei/android/lib/fingerprintidentify/1.2.6/fingerprintidentify-1.2.6.pom
       - file:/home/jp/midhun/ksfe-mobile/node_modules/jsc-android/dist/com/wei/android/lib/fingerprintidentify/1.2.6/fingerprintidentify-1.2.6.pom
       - https://dl.google.com/dl/android/maven2/com/wei/android/lib/fingerprintidentify/1.2.6/fingerprintidentify-1.2.6.pom
       - https://www.jitpack.io/com/wei/android/lib/fingerprintidentify/1.2.6/fingerprintidentify-1.2.6.pom
     Required by:

**Comment by mikehardy** [comment]
Search, then post please
https://github.com/hieuvp/react-native-fingerprint-scanner/issues?q=is%3Aissue+Could+not+find+com.wei.android.lib%3Afingerprintidentify+

Note the "SOLVED" one - duplicate
