### ISSUE TITLE
on run android 

### ISSUE THREAD

**Issue by Mdhun-kakkery** [hieuvp/react-native-fingerprint-scanner#243]
warn Package react-native-fingerprint-scanner contains invalid configuration: "dependency.assets" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
(node:81810) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by mikehardy** [comment]
I just merged #219 - you will need to point your package.json to the commit hash of the commit with the fix though, there is no release with the fix and I'm not really a maintainer here to make a fix...
