### ISSUE TITLE
Support faceid?

### ISSUE THREAD

**Issue by Mad-hu** [hieuvp/react-native-fingerprint-scanner#25]
Support faceid?

**Comment by sbycrosz** [comment]
It seems on iPhone X, iOS will automatically fallback to faceID. 

Apart from the fallback modal that the user will see once, the experience feel seamless
![img_20171108_122432](https://user-images.githubusercontent.com/4867178/32531822-101cb1b6-c481-11e7-8ee1-e608d2cfc5ae.jpg)

**Comment by Mad-hu** [comment]
@sbycrosz  
![qq 20171108124142](https://user-images.githubusercontent.com/13977755/32532014-3108934e-c482-11e7-9adb-d94934dbe108.jpg)

**Comment by haven2world** [comment]
`Error: Device does not support Touch ID`

**Comment by olegfilimonov** [comment]
Would be awesome to have "isSensorAvailable()" return biometry type

**Comment by Aaaaaashu** [comment]
![image](https://user-images.githubusercontent.com/3678166/34479774-88433d1c-efe3-11e7-8c1e-89c6901c3e68.png)

When I unlock with Face ID, the pop-up content is missing icon or text.

**Comment by samratshekhar** [comment]
I wasted quite a lot of time on why faceID was not working on my iPhone X simulator. Hope this helps the next person.
[Face ID for Xcode 9 GM unable to evaluate](https://forums.developer.apple.com/message/265156?et=watches.email.thread#265156)

**Comment by samratshekhar** [comment]
Also, one needs to add following to `info.plist`:
```
<key>NSFaceIDUsageDescription</key>
<string>This app requires Face ID permission to authenticate using Face recognition.</string>
```
Or, try adding `Privacy - Face ID Usage Description` along with the description via GUI. Failing this, app will crash in release mode.

**Comment by edo1493** [comment]
@Aaaaaashu did you figure out a way to show context / text / icon in the faceid popup? or is it just a simulator thing?

**Comment by phillbaker** [comment]
See https://github.com/hieuvp/react-native-fingerprint-scanner/pull/37

**Comment by WeslleyNasRocha** [comment]
@edo1493 did you figure out that?

**Comment by yoavapi** [comment]
> <key>NSFaceIDUsageDescription</key> <string>This app requires Face ID permission to authenticate using Face recognition.</string>

to be added to the readme

**Comment by andhappymoney** [comment]
> ![image](https://user-images.githubusercontent.com/3678166/34479774-88433d1c-efe3-11e7-8c1e-89c6901c3e68.png)
> 
> When I unlock with Face ID, the pop-up content is missing icon or text.
> cc @hieuvp

Have you managed to show the Face ID icon?
