### ISSUE TITLE
android fingerprint sdk update 

### ISSUE THREAD

**Issue by jiang385** [hieuvp/react-native-fingerprint-scanner#26]
hi,
https://github.com/uccmawei/FingerprintIdentify
now android fingerprint sdk has  a latest release is 1.2.1,
when do you update?

**Comment by phillbaker** [comment]
Hi @jiang385 thanks for opening an issue - it looks like there's some initial work to bump this dependency in https://github.com/hieuvp/react-native-fingerprint-scanner/pull/41/commits/410c78bf921e8b54c97341e27d338324ec9ee77d.

**Comment by jiang385** [comment]
oh, Thank you so much for your help! It's great!

**Comment by phillbaker** [comment]
Addressed in https://github.com/hieuvp/react-native-fingerprint-scanner/pull/56.
