### ISSUE TITLE
Any way of removing the "Enter Password" section?

### ISSUE THREAD

**Issue by xwartz** [hieuvp/react-native-fingerprint-scanner#3]
I'm wondering if there is any way to remove this section entirely and only have the 'Cancel' option.

**Comment by hieuvp** [comment]
Yes, iOS does support it!

I will soon release a new version that provide that option.

**Comment by xwartz** [comment]
great!

**Comment by hieuvp** [comment]
Hi @xwartz,

This feature is available on v2.1.3, check out README for further information.
Have a great day!

**Comment by xwartz** [comment]
Wow, thanks @hieuvp .
