### ISSUE TITLE
How to determine touch id is turn off

### ISSUE THREAD

**Issue by tackanoway35** [hieuvp/react-native-fingerprint-scanner#34]
My device is supported touch id but i turn off touch id feature.
isSupported method can check touch id is supported or not
How can i determine that touch id is turn off

**Comment by phillbaker** [comment]
Hi @tackanoway35 the `FingerprintScanner.isSensorAvailable()` will return if a device currently supports touch id. One approach to detect if the user has disabled touch id is to call it before initiating an action using biometrics - that will give the most recent state.

I'm going to close this issue for now, please re-open if things are still not clear!
