### ISSUE TITLE
What should I do when attempts is over?

### ISSUE THREAD

**Issue by 2vm** [hieuvp/react-native-fingerprint-scanner#35]
Right now we have a 5 attempts to pass or fail the touchID. What should we do if user failed all 5 attempts? How can we unlock fingerprint to be able to start its loop again? Or, maybe, it is possible to set an attempts number to smth like 9999? I found 
```java 
public static final int MAX_AVAILABLE_TIMES = Integer.MAX_VALUE;
```
But seems like changing this value has no affect on our attempts count.
Actually I found the way to unlock it - user must scan valid finger 5 times. But i think there must be another way.

**Comment by phillbaker** [comment]
Hi @2vm, I believe that the Android implementations may differ, but for iOS, a user has 5 attempts to use TouchID/FaceID, after that the user must enter the passcode. See https://apple.stackexchange.com/a/138998 for more.

This seems like a reasonable approach to take across platforms as well.

I'm going to close this issue for now as it doesn't seem like an issue with this library specifically, but please re-open if there are further issues!
