### ISSUE TITLE
【iOS】Have any way to use the Native IOS's fingerprint?

### ISSUE THREAD

**Issue by huangxiaohao** [hieuvp/react-native-fingerprint-scanner#4]
hi,I have a question that have any way to use the Native IOS's fingerprint?
I find that your component was create a new page to open the fingerprint function. 
But in the other app, they just use a radio to control the fingerprint.
Thx so much!

**Comment by hieuvp** [comment]
Hi @huangxiaohao,

I'm not sure that I can get your question clearly.
The `authenticate` function is calling the real native code in iOS.
If you're asking for creating a custom layout for TouchID Authentication, the answer is NO.

Reference: https://stackoverflow.com/questions/29692598/custom-touch-id-view

**Comment by huangxiaohao** [comment]
hi @hieuvp thank you for your reply. I am so sorry reply so late.
I will try to use your component on my project, and I will give you feedback ASAP.
Thank you soooo much!😊
