### ISSUE TITLE
Fingerprint Authenticate issue

### ISSUE THREAD

**Issue by lovebehl** [hieuvp/react-native-fingerprint-scanner#42]
i got issue undefined is not a function (evaluting 'e.props.handlePopupDismissed()')

Any idea ?

```
import React,{ Component } from 'react';
import { Platform, ViewPropTypes, Text,View,ScrollView,ImageBackground,Alert,TouchableOpacity,StyleSheet,Dimensions,Image,AsyncStorage,NetInfo } from 'react-native';
import { Navigation } from 'react-native-navigation';
import LinearGradient from 'react-native-linear-gradient';
import axios from 'axios';
import Appurl from './../../config';
import Validation from '../Validation.js';
import Spinner from 'react-native-loading-spinner-overlay';
import * as userActions from '../actions/userActions';
import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import ModalDropdown from 'react-native-modal-dropdown';
import DeviceInfo from 'react-native-device-info';
import {Container,H1,Button,Content,Left,Body,Right,Icon} from 'native-base';
import {GoogleSignin, GoogleSigninButton} from 'react-native-google-signin';
import FBSDK from 'react-native-fbsdk';
import FingerprintPopup from './Fingerprint';
import FingerprintScanner from 'react-native-fingerprint-scanner';
import ShakingText from './ShakingText';
import styles from './FingerprintDesign';
import PropTypes from 'prop-types';

const {
  LoginManager,
  AccessToken
} = FBSDK;

class TestAndroid extends Component {

    constructor(props) {
      super(props);
      this.state = {
        errorMessage: undefined,
      };
    }
  
    componentDidMount() {
        FingerprintScanner
        .authenticate({ onAttempt: this.handleAuthenticationAttempted })
        .then(() => {
          this.props.handlePopupDismissed();
          Alert.alert('Fingerprint Authentication', 'Authenticated successfully');
        })
        .catch((error) => {
          this.setState({ errorMessage: error.message });
          this.description.shake();
        });
    }
    componentWillUnmount() {
        FingerprintScanner.release();
      }

    
    handleAuthenticationAttempted = (error) => {
        this.setState({ errorMessage: error.message });
        this.description.shake();
      };
  
    render() {
      const { errorMessage } = this.state;
      const { style, handlePopupDismissed } = this.props;
  
      return (
        <View style={styles.container}>
        <View style={[styles.contentContainer, style]}>

          <Image
            style={styles.logo}
            source={require('./../../images/ic_inbox_active.png')}
          />

          <Text style={styles.heading}>
            Fingerprint{'\n'}Authentication
          </Text>
          <ShakingText
            ref={(instance) => { this.description = instance; }}
            style={styles.description(!!errorMessage)}>
            {errorMessage || 'Scan your fingerprint on the\ndevice scanner to continue'}
          </ShakingText>

          <TouchableOpacity
            style={styles.buttonContainer}
            onPress={handlePopupDismissed}
          >
            <Text style={styles.buttonText}>
              BACK TO MAIN
            </Text>
          </TouchableOpacity>

        </View>
      </View>
      );
    }
  }

  TestAndroid.propTypes = {
    style: ViewPropTypes.style,
    handlePopupDismissed: PropTypes.func.isRequired,
  };


function mapStateToProps(state, ownProps) {
  return {
      user: state.user
  };
}
function mapDispatchToProps(dispatch) {
  return {
      actions: bindActionCreators(userActions, dispatch)
  };
}
export default connect(mapStateToProps, mapDispatchToProps)(TestAndroid);
```

**Comment by rajscet** [comment]
i got the same

**Comment by phillbaker** [comment]
Hi @lovebehl, @rajscet I've recently been added to this repo as a collaborator and am trying to get up to speed on the different issues. Is this issue still relevant?

**Comment by VinCodeTheWeb** [comment]
I have the same issue... I've done everything correct but can't figure out what's happening...

`import React, { Component, PropTypes } from "react";
import { AlertIOS } from "react-native";
import FingerprintScanner from "react-native-fingerprint-scanner";

class FingerprintPopup extends Component {
  componentDidMount() {
    FingerprintScanner.authenticate({
      description: "Scan your fingerprint on the device scanner to continue"
    })
      .then(() => {
        this.props.handlePopupDismissed();
        AlertIOS.alert("Authenticated successfully");
      })
      .catch(error => {
        this.props.handlePopupDismissed();
        AlertIOS.alert(error.message);
      });
  }

  render() {
    return false;
  }
}

// FingerprintPopup.propTypes = {
//   handlePopupDismissed: PropTypes.func.isRequired
// };

export default FingerprintPopup;


import React, { Component } from "react";
import {
  StyleSheet,
  Text,
  View,
  TextInput,
  ScrollView,
  TouchableOpacity,
  AsyncStorage
} from "react-native";
import Note from "./Note";
import FingerprintPopup from "./FingerprintPopup";
export default class Main extends Component {
  constructor(props) {
    super(props);
    this.state = {
      noteArray: [],
      noteText: ""
    };
  }

  addNote() {
    if (this.state.noteText) {
      var d = new Date();
      this.state.noteArray.push({
        date: d.getFullYear() + "/" + (d.getMonth() + 1) + "/" + d.getDate(),
        note: this.state.noteText
      });
      this.setState({
        noteArray: this.state.noteArray,
        noteText: ""
      });
    }
  }

  deleteNote(index) {
    if (this.state.noteArray.length !== 0) {
      this.state.noteArray.splice(index, 1);
      this.setState({ noteArray: this.state.noteArray });
      console.log(this.state.noteArray);
    }
  }
  render() {
    let notes = this.state.noteArray.map((val, key) => {
      return (
        <Note
          key={key}
          keyval={key}
          val={val}
          deleteMethod={() => this.deleteNote(key)}
        />
      );
    });
    return (
      <View style={styles.container}>
        <View style={styles.header}>
          <FingerprintPopup
            handlePopupDismissed={() => console.log("It Workded!")}
          />
          <Text style={styles.headerText}>- DaVinCode -</Text>
        </View>
        <ScrollView style={styles.scrollContainer}>{notes}</ScrollView>
        {this.state.noteText.length > 0 && (
          <TouchableOpacity
            onPress={this.addNote.bind(this)}
            style={styles.addButton}
          >
            <Text style={styles.addButtonText}>
              {this.state.noteText.length !== 0 ? "ADD" : "+"}
            </Text>
          </TouchableOpacity>
        )}
        <View style={styles.footer}>
          <TextInput
            style={styles.textInput}
            onChangeText={noteText => this.setState({ noteText })}
            value={this.state.noteText}
            placeholder="Add a note..."
            placeholderTextColor="white"
            underlineColorAndroid="transparent"
          />
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  header: {
    backgroundColor: "#E91E63",
    alignItems: "center",
    justifyContent: "center",
    borderBottomWidth: 10,
    borderBottomColor: "#DDD"
  },
  headerText: {
    color: "white",
    fontSize: 18,
    padding: 26
  },
  scrollContainer: {
    flex: 1,
    marginBottom: 100
  },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 10
  },
  textInput: {
    alignSelf: "stretch",
    color: "#fff",
    padding: 20,
    backgroundColor: "#252525",
    borderTopWidth: 2,
    borderTopColor: "#EDEDED"
  },
  addButton: {
    position: "absolute",
    zIndex: 11,
    right: 20,
    bottom: 90,
    backgroundColor: "#E91E63",
    width: 90,
    height: 90,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    elevation: 8
  },
  addButtonText: {
    color: "#FFF",
    fontSize: 24
  }
});
`

**Comment by sanjaymhj** [comment]
@VinCodeTheWeb could you post the error log

**Comment by viv3kk** [comment]
handlePopupDismissed 
TypeError: _this2.props.handlePopupDismissed is not a function

**Comment by phillbaker** [comment]
@viv3kk @sanjaymhj @VinCodeTheWeb this issue seems very similar to:
*  https://github.com/hieuvp/react-native-fingerprint-scanner/issues/52 
* https://github.com/hieuvp/react-native-fingerprint-scanner/issues/8

Can you try the workaround posted in https://github.com/hieuvp/react-native-fingerprint-scanner/issues/8#issuecomment-405924952 or https://github.com/hieuvp/react-native-fingerprint-scanner/issues/58#issuecomment-429626522?

**Comment by phillbaker** [comment]
Hi all, following up here - is this still an issue?

**Comment by sanjaymhj** [comment]
Not sure if this is relevant but... https://github.com/hieuvp/react-native-fingerprint-scanner/issues/58#issuecomment-429626522 was my conclusion... haven't found the solution. Please post if you find solution :)

**Comment by phillbaker** [comment]
Going to close as it seems like a configuration issue and not an issue with this library.
