### ISSUE TITLE
Enrollment Fingerprint Changed

### ISSUE THREAD

**Issue by SaruwatariSagittario** [hieuvp/react-native-fingerprint-scanner#47]
hi, anyone have a way to listen when the enrolled fingerprint is added or removed ?

**Comment by phillbaker** [comment]
Hi @SaruwatariSagittario, I've recently been added as a collaborator on this repo. Can you give an example workflow to help illustrate the problem you're trying to solve?

**Comment by phillbaker** [comment]
I believe this is a dupe of #66, going to close as there hasn't been any follow up.
