### ISSUE TITLE
External scanning device

### ISSUE THREAD

**Issue by simranaurora** [hieuvp/react-native-fingerprint-scanner#50]
Can this work if I use external biometric finger scanner device ?

**Comment by atultiwari1996** [comment]
I use morpho biometric external device but not working . is this possible using this package.

**Comment by phillbaker** [comment]
Hi @atultiwari1996 the underlying android library used here is https://github.com/uccmawei/FingerprintIdentify, can you determine if that library supports your device?

**Comment by phillbaker** [comment]
I'm going to close this issue as outside of the scope of this library.

I did find this article which documents building a native interface to fingerprint scanners: https://medium.com/touch4it/fingerprint-external-scanner-with-usb-database-sdk-64c3ec5ea82d. That native code might be able to be integrated into a similar interface as this library, however, it would be hard to test and support as each device may be different.
