### ISSUE TITLE
call function when authenticated successfully

### ISSUE THREAD

**Issue by dinhtu0802** [hieuvp/react-native-fingerprint-scanner#51]
hi @hieuvp !
<img width="684" alt="screen shot 2018-07-28 at 4 55 02 pm" src="https://user-images.githubusercontent.com/40747369/43355463-02ee6a64-9287-11e8-8438-9ea84ff58c7e.png">
 i want navigate when  authenticated successfully but cant.
Please help me!

**Comment by phillbaker** [comment]
Hi @dinhtu0802 thanks for opening an issue. I've recently been added as a collaborator on this repo. 

Unfortunately, this doesn't sound like an issue with this library, so I'm going to close this issue for now. Please reopen if you can provide a specific error or issue related to this library. Thanks!
