### ISSUE TITLE
Get the Asymmetric Keys

### ISSUE THREAD

**Issue by joshuachinemezu** [hieuvp/react-native-fingerprint-scanner#54]
Can you get the Asymmetric Keys from any user's fingerprint or even just the public key ?

Looks like you can only verify a fingerprint which was beforehand stored into Android Keystore by the user. Is that correct ?

Is there a way to get the asymmetric keys and probably save it to your server?

**Comment by phillbaker** [comment]
Hi @joshuachinemezu I'm not quite sure I follow - can you provide any links to where this is possible via the [Android library](https://github.com/uccmawei/FingerprintIdentify) or the iOS native libraries?

**Comment by joshuachinemezu** [comment]
Thanks @phillbaker this [https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt.CryptoObject](link) is saying something about getCipher and cyrptoObject, so I was thinking one of them can get the unique asymmetric keys of a user that I can save to my database and use it to identify a particular... What do you think @phillbaker @hieuvp

**Comment by joshuachinemezu** [comment]
Ok what I am trying to achieve is a time attendance software that when a staff comes to work the just place their thumb on the scanner and it queries for that staff on the db using the asymmetric key that has been previously saved to the db thus registering the time that the staff came to work. 
Hope you understand, ask me if you need any further clarifications.Thanks @phillbaker @hieuvp @tommeier @chris-griffin @hoangnm @xwartz

**Comment by WeslleyNasRocha** [comment]
@joshuachinemezu i think i could understand what you want, but this is something i think only the android api provide, but the [library](https://github.com/uccmawei/FingerprintIdentify) this package relies onto, does not provide this kind of functionality, it only compares then returns if it works or not and why not.

**Comment by Kyonru** [comment]
Maybe you should try something like [this](https://github.com/SelfLender/react-native-biometrics).

**Comment by phillbaker** [comment]
Thanks @Kyonru, seems like this is appropriate for the library you found or another independent library. Going to close this issue for now as outside the scope of this project. Thanks!
