### ISSUE TITLE
Device in lockout

### ISSUE THREAD

**Issue by WeslleyNasRocha** [hieuvp/react-native-fingerprint-scanner#55]
Would be nice if it provides an specific error when the device is in lockout,
[docs](https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager.html#FINGERPRINT_ERROR_LOCKOUT)

**Comment by WeslleyNasRocha** [comment]
Do you guys have any rules of contribution?
I think I made it.

**Comment by phillbaker** [comment]
Great! There's some work being done on this in https://github.com/hieuvp/react-native-fingerprint-scanner/pull/44 and https://github.com/hieuvp/react-native-fingerprint-scanner/pull/41/commits/f07e5d9b31e5b78ed28ba4508521d1c43b3b5f39, but if you have a specific change that you'd like to PR, that'd great.

General rules of thumb are to follow the styles and conventions of the repo as they exist currently.

**Comment by WeslleyNasRocha** [comment]
Ow, thx. 
I guess since #44 its from june, its just an small change

**Comment by WeslleyNasRocha** [comment]
and in [f07e5d9](https://github.com/hieuvp/react-native-fingerprint-scanner/commit/f07e5d9b31e5b78ed28ba4508521d1c43b3b5f39) it is not in npm i guess

**Comment by WeslleyNasRocha** [comment]
#56 here it is, just a small change for a quick support to device locked

**Comment by phillbaker** [comment]
Fixed in https://github.com/hieuvp/react-native-fingerprint-scanner/pull/56.
