### ISSUE TITLE
Document iOS FaceID Info.plist requirement

### ISSUE THREAD

**Issue by huytran123** [hieuvp/react-native-fingerprint-scanner#57]
Please add config add key "NSFaceIDUsageDescription" with value "Need your face to unlock secrets!" to run Face ID on iPhone X.

If not have that key. I can not use Face ID

**Comment by phillbaker** [comment]
Hi @huytran123, thanks for opening an issue! We should definitely document this better in the Readme.

An example of adding to the `Info.plist` is:

```
<key>NSFaceIDUsageDescription</key>
<string>$(PRODUCT_NAME) Authentication</string>
```
