### ISSUE TITLE
Cannot read property 'isSensorAvailable' of undefined

### ISSUE THREAD

**Issue by fauzynurn** [hieuvp/react-native-fingerprint-scanner#58]
I tried to clone the example and ran it on my android. but it showed the error that the property 'isSensorAvailable' is undefined. I tried to debug the FingerprintScanner and i saw the isSensorAvailable function there. Here's some screenshoot : 

(the problem i faced)
![screenshot](https://user-images.githubusercontent.com/28076295/46241081-cda1fe80-c3db-11e8-9a28-95af2a165460.jpg)

(the debug i have done)
![captunnre](https://user-images.githubusercontent.com/28076295/46241093-19ed3e80-c3dc-11e8-9d4e-dd0dd505d9e5.PNG)

(the result)
![captummre](https://user-images.githubusercontent.com/28076295/46241096-22457980-c3dc-11e8-9ef4-c0adfcd0f625.PNG)

What exactly the problem i face? thanks.

**Comment by fauzynurn** [comment]
Solved. It is because i created my project with create-react-app instead of react-native init. My mistake. Thanks .

**Comment by sanjaymhj** [comment]
I am facing the same issue.

Solution [#8 comment](https://github.com/hieuvp/react-native-fingerprint-scanner/issues/8#issuecomment-405924952)  also doesnot work for me.

**Comment by phillbaker** [comment]
@sanjaymhj did you make sure that the modules are linked correctly and re-compile the app?

**Comment by sanjaymhj** [comment]
@phillbaker yes. I have tried both react-native link `react-native-fingerprint-scanner` and manual configuration. Both results to the same issue. Am I missing something?

**Comment by sanjaymhj** [comment]
@phillbaker thanks for the help. Don't know if this is relevant or correct but I fixed it by removing `ReactNativeHost` from `MainApplication`. `react-native-navigation` was causing a problem in my case. But between `react-native-navigation`: 1.x.x, `react-native-fingerprint-scanner`: 2.5.0 and `react-native-fbsdk`: 0.7.0, I could only include 2 libraries in my project.

**Comment by dan-Scripts** [comment]
This issue still persist, i had to create new clean project and library example code  still get [TypeError: Cannot read property 'authenticate' of null] on android. Any solution?
