### ISSUE TITLE
FaceID not working

### ISSUE THREAD

**Issue by nehab05a** [hieuvp/react-native-fingerprint-scanner#60]
Application crashes while authenticating for FaceID.

FingerprintScanner
      .authenticate({ description: 'Scan your fingerprint on the device scanner to continue' })
      .then(() => {
        this.props.onSuccess();
      })
      .catch((error) => {
        this.props.onCancel();
      });

This piece of code fails for faceID however, TouchID/Fingerprint works perfectly fine for both iOS and android.

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.8.0
  Yarn: 1.3.2
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.1 => 16.5.2
  react-native: ^0.55.0 => 0.55.3

'react-native-fingerprint-scanner'  => 2.5.0v
using iPhone X (11.3)

**Comment by nehab05a** [comment]
Closing this issue as I found out a solution. Need to set permission for FaceID on iOS device.

Added following in **Info.plist** to get it working
**<key>NSFaceIDUsageDescription</key>
<string>Enabling Face ID allows you quick and secure access to your account.</string>**

**Comment by phillbaker** [comment]
@nehab05a yup, included in the readme at https://github.com/hieuvp/react-native-fingerprint-scanner#extra-configuration, I guess not the most obvious, sorry! Where would be a better spot to put it?

**Comment by nehab05a** [comment]
@phillbaker In my opinion we should be having a Permission section mentioning this stuff
Something like this:

### App Permissions

Add the following permissions to their respective files:

In your `AndroidManifest.xml`:

```xml
<uses-permission android:name="android.permission.USE_FINGERPRINT" />
```

In your `Info.plist`:

```xml
<key>NSFaceIDUsageDescription</key>
<string>Enabling Face ID allows you quick and secure access to your account.</string>
```

**Comment by phillbaker** [comment]
Makes sense, could you do a PR?

**Comment by nehab05a** [comment]
Created one as requested.

**Comment by akash4320** [comment]
Above mentioned all the process have been done , but it doesn't solve for FaceID in Android and ios both.this problem is in react native fingerprint scanner as well as react-native-touchId

**Comment by magnusideas** [comment]
test

**Comment by Nawalnazari** [comment]
> Above mentioned all the process have been done , but it doesn't solve for FaceID in Android and ios both.this problem is in react native fingerprint scanner as well as react-native-touchId

yes also face the same issue,
