### ISSUE TITLE
Device does not support finger print scanner 

### ISSUE THREAD

**Issue by sasanrk** [hieuvp/react-native-fingerprint-scanner#62]
This is weird, because there is a phone **has supported finger print** but getting this error :
Device does not support finger print scanner 

![device_has_not_support_small](https://user-images.githubusercontent.com/26356747/47616455-1e3b7300-dad2-11e8-9bf4-a5bb8d936ff2.jpeg)

**It happened just for this phone, What do you think ?**
device : huawei mT7-l09

**Comment by Ramin-Bateni** [comment]
Are you sure that you used the following instructions in your project correctly?

**Android**
Open up `android/app/src/main/java/[...]/MainActivity.java`
Add import com.hieuvp.fingerprint.ReactNativeFingerprintScannerPackage; to the imports at the top of the file
Add new `ReactNativeFingerprintScannerPackage()` to the list returned by the `getPackages()` method
Append the following lines to `android/settings.gradle`:
```
include ':react-native-fingerprint-scanner'
project(':react-native-fingerprint-scanner').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fingerprint-scanner/android')
```
Insert the following lines inside the dependencies block in `android/app/build.gradle:`
`compile project(':react-native-fingerprint-scanner')`

**App Permissions**
Add the following permissions to their respective files:

In your `AndroidManifest.xml`:

`<uses-permission android:name="android.permission.USE_FINGERPRINT" />
`
Also add this permission for Android API 28 and later:
`<uses-permission android:name="android.permission.USE_BIOMETRIC" />`

**Comment by phillbaker** [comment]
@sasanrk did that fix the issue? Should this issue be closed now?

**Comment by sasanrk** [comment]
@phillbaker 
@Ramin-Bateni 

I'm still **waiting** for the **test unit** response. If I get the answer I will share the result here

**Comment by phillbaker** [comment]
Going to close this issue for now since there hasn't been an update, but please re-open if there's additional detail.

**Comment by imdaniele** [comment]
Any news about this?

I have the same exact problem.
I followed all the instructions, and this sometimes happens.

I also used another biometric library in the **catch** block of **isSensorAvailable()** and the other library says that Fingerprint is correctly available and it also authenticates.
