### ISSUE TITLE
compile deprecation

### ISSUE THREAD

**Issue by GuusBaggen** [hieuvp/react-native-fingerprint-scanner#64]
compile in android/build.gradle should be replaced with implementation

![image](https://user-images.githubusercontent.com/22646819/49583034-2d2a0680-f957-11e8-916e-976200e066ac.png)

**Comment by phillbaker** [comment]
Just noting that this is a breaking change for gradle 3+

**Comment by carloscuatin** [comment]
some progress with this ?, I see that in `react-native-fs` launched a version with this arrangement and in the readme they clarify which one to use according to the version of react native

**Comment by phillbaker** [comment]
Fixed in https://github.com/hieuvp/react-native-fingerprint-scanner/pull/104
