### ISSUE TITLE
[ANDROID] Installation Instructions Incomplete

### ISSUE THREAD

**Issue by cmejet** [hieuvp/react-native-fingerprint-scanner#65]
Instructions do not include instructions to add the package to the MainApplicationJava. It is present in the Android Example code but not in the directions for setup.

Should instruct users to add the import statement to the MainApplicationJava as well as the package to the getPackages function.

import com.hieuvp.fingerprint.ReactNativeFingerprintScannerPackage;

new ReactNativeFingerprintScannerPackage()

**Comment by phillbaker** [comment]
Hi @cmejet, those are typically added by `react-native link` ([readme link](https://github.com/hieuvp/react-native-fingerprint-scanner#automatic-configuration)). There are also [manual configuration instructions](https://github.com/hieuvp/react-native-fingerprint-scanner#android). 

Did these instructions not work?

**Comment by cmejet** [comment]
@phillbaker react-native link adds the project to the settings gradle and the project gradle files, and the import but does not add the package in the MainApplication.java

I'm sorry I missed the import line on the instructions over shadowed by the "Extra Configuration" section :) My bad, it all starts to blur.
