### ISSUE TITLE
isSensorAvailable function doesn't get correct fingerprint state 

### ISSUE THREAD

**Issue by YoujustneedAjob** [hieuvp/react-native-fingerprint-scanner#66]
here's  a thing,  I use isSensorAvailable  method in ComponentDidMount , it's works; 
when I back homePage, delete fingerprint in system, and back to App , use isSensorAvailable  method , then get wrong state; seem like it's just works in first time? 

here my code:   
```
componentDidMount(){
        FingerprintScanner.isSensorAvailable().then((biometryType) => {
            console.log(biometryType);
            this.setState({ isSupportFinger: true});
        }).catch((error) => { 
          ...do something
       })
}

// when change AppState, active to back, back to active; 
AppStateChangedListener(appState){
   //when appState is active ,check fringerprint isSensorAvailable
   FingerprintScanner.isSensorAvailable().then((biometryType) => {
            console.log(biometryType);
            this.setState({ isSupportFinger: true});
        }).catch((error) => { 
          ...do something
       })
  // can't return right state;  same as first time  (ComponentDidMount)
}
```

**Comment by phillbaker** [comment]
This technique does work - is your AppStateChangedListener getting called? I've seen the `isSensorAvailable` called in `componentWillReceiveProps` which could be too frequent, but does make sure that it's called when something changes.

**Comment by YoujustneedAjob** [comment]
> This technique does work - is your AppStateChangedListener getting called? I've seen the `isSensorAvailable` called in `componentWillReceiveProps` which could be too frequent, but does make sure that it's called when something changes.

not props change called 'isSensorAvailable' , it's 'AppState'.  
MyApp back to Home Screen, delete fringerprint in system, then go back MyApp, AppState changed listener called 'isSensorAvailable', and the fingerprint setting state is not correct.

**Comment by phillbaker** [comment]
To clarify - `.release()` needs to be called for android. I'll update the example to clarify this.
