### ISSUE TITLE
List of available sensors

### ISSUE THREAD

**Issue by icastillejogomez** [hieuvp/react-native-fingerprint-scanner#69]
Any way to get the list with all available sensor, not in one device but in all

**Comment by phillbaker** [comment]
@icastillejogomez can you clarify the question and/or give an example? I'm not sure I follow - this library can only be used on one device at a time and each device typically only has one sensor.

**Comment by icastillejogomez** [comment]
In new Huawei Android (P Smart +) for example, has facial recognition and fingerprint sensor. I made some test (disable fingerprint sensor and enable and enrolle "face id") and app show me the fingerprint sensor.

Exists any way to get **all** biometric mobile sensors?

The mobile industry is growing so fast the last years.... Thanks for all!!!

**Comment by phillbaker** [comment]
Interesting! It'd have to be supported in the upstream library we use https://github.com/uccmawei/FingerprintIdentify, probably best to open a ticket there.

**Comment by icastillejogomez** [comment]
Okay. I think the best choice is that repo admins open the issue there.
