### ISSUE TITLE
Unable to build production app

### ISSUE THREAD

**Issue by viv3kk** [hieuvp/react-native-fingerprint-scanner#72]
Unable to build production app with RN 0.57 and android

What went wrong:
Execution failed for task ':react-native-fingerprint-scanner:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  Output:  /home/justdial/react_projects/myjd_code/hrlite/node_modules/react-native-fingerprint-scanner/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:7: error: resource android:attr/colorError not found.
  /home/justdial/react_projects/myjd_code/hrlite/node_modules/react-native-fingerprint-scanner/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:11: error: resource android:attr/colorError not found.
  /home/justdial/react_projects/myjd_code/hrlite/node_modules/react-native-fingerprint-scanner/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
  /home/justdial/react_projects/myjd_code/hrlite/node_modules/react-native-fingerprint-scanner/android/build/intermediates/res/merged/release/values/values.xml:226: error: resource android:attr/fontStyle not found.
  /home/justdial/react_projects/myjd_code/hrlite/node_modules/react-native-fingerprint-scanner/android/build/intermediates/res/merged/release/values/values.xml:226: error: resource android:attr/font not found.
  /home/justdial/react_projects/myjd_code/hrlite/node_modules/react-native-fingerprint-scanner/android/build/intermediates/res/merged/release/values/values.xml:226: error: resource android:attr/fontWeight not found.
  error: failed linking references.
  
  Command: /home/justdial/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.0-4818971-linux.jar/6939bd2e3845c1dff5341c63b61e5547/aapt2-3.2.0-4818971-linux/aapt2 link -I\
          /home/justdial/Android/Sdk/platforms/android-25/android.jar\
          --manifest\
          /home/justdial/react_projects/myjd_code/hrlite/node_modules/react-native-fingerprint-scanner/android/build/intermediates/aapt_friendly_merged_manifests/release/processReleaseManifest/aapt/AndroidManifest.xml\
          -o\
          /tmp/aapt-5994702613927831493-out\
          -R\
          /home/justdial/react_projects/myjd_code/hrlite/node_modules/react-native-fingerprint-scanner/android/build/intermediates/res/compiled/release/layout_abc_screen_content_include.xml.flat\

**Comment by viv3kk** [comment]
Resolved by updating build.gradle 
```
compileSdkVersion 28
buildToolsVersion "28.0.2"
```

**Comment by shuffledex** [comment]
same error here. where we need to change the config?
