### ISSUE TITLE
face id is not working on some devices

### ISSUE THREAD

**Issue by opolyo01** [hieuvp/react-native-fingerprint-scanner#73]
I have tested with 4 iphoneX devices, and 2 out of 4 fail on
```
import TouchID from 'react-native-fingerprint-scanner';
return await TouchID.authenticate(param) method.
```
It always crashes on iphone X simulator.

I am using - "react-native-fingerprint-scanner": "^2.5.0",

**Comment by phillbaker** [comment]
Hi @opolyo01 can you share the error logs you're seeing?

**Comment by opolyo01** [comment]
Thanks, I didn't put permissions.  I was upgrading the version of React Native, and those permissions got blown away inside of info.plist.
