### ISSUE TITLE
isSensorAvailable()  method returns boolean(true or false) value instead of biometryType value(Touch ID,Face ID)

### ISSUE THREAD

**Issue by chethan14** [hieuvp/react-native-fingerprint-scanner#74]
FingerprintScanner.isSensorAvailable().then(biometryType => {
                    console.log(
                        "fingerprintScannerAvailable available",
                        biometryType
                    ); }).catch(err => {
                    console.log("fingerprintScannerAvailable not available");    
                });

React-Native version:0.56.0
   "react-native-fingerprint-scanner": "^2.3.2",

actual result: isSensorAvailable() return true if any(touch ID or face ID) of the sensor available otherwise false
expected result: it should return biometryType value(value: Touch ID,Face ID). currently i am getting boolean value

**Comment by phillbaker** [comment]
@chethan14 can you verify that you're running the latest version of react-native-fingerprint-scanner, the latest released version is 2.5.0: https://www.npmjs.com/package/react-native-fingerprint-scanner

**Comment by chethan14** [comment]
Hi @phillbaker, after upgrading react-native-fingerprint-scanner to a latest version 2.5.0 its working fine now. Thanks for your feedback
