### ISSUE TITLE
Plugin readme, small mistake for Android

### ISSUE THREAD

**Issue by Dawqss** [hieuvp/react-native-fingerprint-scanner#76]
In readme at point Android 1.

> Open up android/app/src/main/java/[...]/MainActivity.java

it should not be `Open up android/app/src/main/java/[...]/MainApplication.java ?`

[MainApplication.java](https://github.com/hieuvp/react-native-fingerprint-scanner/blob/master/examples/android/app/src/main/java/com/examples/MainApplication.java)

**Comment by phillbaker** [comment]
Quite right! Could you do a PR @Dawqss ?
