### ISSUE TITLE
Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by AndroidHive12** [hieuvp/react-native-fingerprint-scanner#77]
I am not able to build and run the examples project which included in this repository. Getting the below-mentioned error. I issued the following command in the terminal to build the project.
react-native run-android
info Starting JS server...
info Building and installing the app on the device (cd android && ./gradlew app:installDebug)...
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: ./gradlew app:installDebug

**Comment by phillbaker** [comment]
Can you share your react native version, java version and other details of your environment?
