### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by zqderek** [hieuvp/react-native-fingerprint-scanner#8]
i do the same as your read.me  and the app can run. but!  at the app start i got some error
undefined is not an object(evaluating 'ReactNativeFingerprintScanner.isSensorAvailable').

i dont know what's wrong

**Comment by AunMSheikh** [comment]
If you could post your implementation we might be able to debug it for you

**Comment by chapeljuice** [comment]
I'm getting that error too, only for **ReactNativeFingerprintScanner.authenticate**.

Any ideas?

```
  import FingerprintScanner from 'react-native-fingerprint-scanner'

  componentDidMount() {
    if (Platform.OS === 'ios') {
      console.log('ios device, trying to use fingerprint scanner')
      // iOS code only
      FingerprintScanner
        .authenticate({ description: 'Scan your fingerprint on the device scanner to continue' })
        .then(() => {
          AlertIOS.alert('Authenticated successfully')
        })
        .catch((error) => {
          console.log(error)
        })
    } else if (Platform.OS === 'android') {
      console.log('android device, trying to use fingerprint scanner')
      // android code only
      FingerprintScanner
        .authenticate({ onAttempt: this.handleAuthenticationAttempted })
        .then(() => {
          Alert.alert('Fingerprint Authentication', 'Authenticated successfully')
        })
        .catch((error) => {
          console.log(error)
        })
    }
  }

  componentWillUnmount() {
    if (Platform.OS === 'android') {
      FingerprintScanner.release()
    }
  }

**Comment by foxmicha** [comment]
I am getting the same error when attempting to import the FingerprintScanner as a require statement. I'm doing this to attempt to clear up some TypeScript errors, since there doesn't appear to be any typings for this project.

This works fine but generates a TypeScript error:
import FingerprintScanner from "react-native-fingerprint-scanner";

This throws an undefined object exception:
const {FingerprintScanner} = require("react-native-fingerprint-scanner");

**Comment by antbaobao** [comment]
so anyone has solved this problem ?

**Comment by foxmicha** [comment]
You should be able to do:

`const {FingerprintScanner} = require("react-native-fingerprint-scanner").default;`

This ended up being the workaround for me.
