### ISSUE TITLE
[iOS] (TouchID) Dialog sometimes not showing on iOS 13

### ISSUE THREAD

**Issue by LasseSLambertsen** [hieuvp/react-native-fingerprint-scanner#98]
Hi, I've just implemented this library, but experiencing some problems on iOS 13.

The TouchID dialog, doesn't always show, but when touching the fingerprint scanner, it quickly shows and authenticates.

I'm running newest RN 0.61.1 and react-native-fingerprint-scanner 3.0.0

**Comment by phillbaker** [comment]
Thanks for opening an issue. Is this happening on a real device or the
simulator? What model is it?

**Comment by LasseSLambertsen** [comment]
Happening on a real iPhone 8

**Comment by ItsNoHax** [comment]
Also running into this: I assume it's to do with some new iOS 13 change.

**Comment by phillbaker** [comment]
It looks like this is due to an upstream bug in iOS 13 (so not something this library can address). Sources:
* https://stackoverflow.com/questions/58195407/on-ios-13-the-biometric-authentication-alert-does-not-show-on-older-phones
* https://9to5mac.com/2019/09/30/ios-13-iphone-touch-id-login-bug/

**Comment by phillbaker** [comment]
There are some reports that iOS 13.1.3 fixes this: https://github.com/EddyVerbruggen/cordova-plugin-touch-id/issues/84#issuecomment-544321805

**Comment by ItsNoHax** [comment]
Yes, I am also seeing this being fixed with iOS 13.1.3

**Comment by phillbaker** [comment]
Going to close, thanks all!
